# Generated by Django 5.1.4 on 2024-12-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(verbose_name='Формула')),
                ('source', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Источник')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
    ]
